# Site settings
title: jalindr.in
email: jalindr@live.in
baseurl: ""
url: "https://jalindr.github.io"
github_username: jalindr
# Build settings
markdown: kramdown


# Third-party services
# just leave someone empty to disable it
google_analytics: UA-73655797-1
#disqus_shortname: 
